# Generated by Django 6.0.3 on 2026-06-23 07:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('kode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('sks', models.IntegerField(default=2)),
                ('jurusan', models.CharField(default='Semua Jurusan', max_length=100)),
                ('kategori', models.CharField(default='Wajib', max_length=50)),
                ('kelompok', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodeYudisium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_periode', models.CharField(max_length=100)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TtdPetugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_petugas', models.CharField(help_text='Nama Lengkap beserta Gelar', max_length=150)),
                ('jabatan', models.CharField(help_text='Contoh: Ketua Program Studi, Dekan, Kepala Perpus', max_length=100)),
                ('file_ttd', models.ImageField(blank=True, help_text='Upload gambar tanda tangan transparan format PNG', null=True, upload_to='yudisium/ttd_master/')),
                ('is_active', models.BooleanField(default=True, help_text='Set aktif jika petugas ini yang berwenang menandatangani surat sekarang')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tanda Tangan Petugas',
                'verbose_name_plural': 'Tanda Tangan Petugas',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID unik sebagai pengganti integer ID', primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('MAHASISWA', 'Mahasiswa'), ('BAAK', 'Bagian Administrasi Akademik Kemahasiswaan'), ('AKADEMIK', 'Akademik'), ('PERPUS', 'Perpustakaan'), ('SUPERADMIN', 'Super Admin')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('program_studi', models.CharField(max_length=100)),
                ('angkatan', models.IntegerField()),
                ('no_hp', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('pesan', models.TextField()),
                ('tipe', models.CharField(blank=True, choices=[('BERKAS_MASUK', 'Berkas Masuk'), ('VALIDASI_DITERIMA', 'Validasi Diterima'), ('VALIDASI_DITOLAK', 'Validasi Ditolak'), ('SURAT_BEBAS_PERPUS', 'Surat Bebas Perpustakaan'), ('PENDAFTARAN_YUDISIUM', 'Pendaftaran Yudisium'), ('VERIFIKASI_YUDISIUM', 'Verifikasi Yudisium')], default='BERKAS_MASUK', max_length=50, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PendaftaranYudisium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
                ('status_akhir', models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('LULUS', 'Lulus'), ('TIDAK_LULUS', 'Tidak Lulus')], default='MENUNGGU', max_length=20)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistem_yudisium.mahasiswa')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistem_yudisium.periodeyudisium')),
            ],
            options={
                'unique_together': {('mahasiswa', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='BerkasAkademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_ijazah', models.FileField(blank=True, null=True, upload_to='yudisium/akademik/')),
                ('foto_akte', models.FileField(blank=True, null=True, upload_to='yudisium/akademik/')),
                ('foto_ktp', models.FileField(blank=True, null=True, upload_to='yudisium/akademik/')),
                ('foto_3x4', models.FileField(blank=True, null=True, upload_to='yudisium/akademik/')),
                ('status', models.CharField(choices=[('MENUNGGU', 'MENUNGGU'), ('DISETUJUI', 'DISETUJUI'), ('DITOLAK', 'DITOLAK')], default='MENUNGGU', max_length=20)),
                ('catatan_akademik', models.TextField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pendaftaran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='akademik', to='sistem_yudisium.pendaftaranyudisium')),
            ],
        ),
        migrations.CreateModel(
            name='BebasPerpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_abstrak', models.FileField(blank=True, null=True, upload_to='yudisium/perpus/abstrak/', verbose_name='File Abstrak PDF')),
                ('bagian_awal', models.FileField(blank=True, null=True, upload_to='yudisium/perpus/awal/')),
                ('bab1', models.FileField(blank=True, null=True, upload_to='yudisium/perpus/bab1/')),
                ('bab2', models.FileField(blank=True, null=True, upload_to='yudisium/perpus/bab2/')),
                ('bab3', models.FileField(blank=True, null=True, upload_to='yudisium/perpus/bab3/')),
                ('bab4', models.FileField(blank=True, null=True, upload_to='yudisium/perpus/bab4/')),
                ('bab5', models.FileField(blank=True, null=True, upload_to='yudisium/perpus/bab5/')),
                ('daftar_pustaka', models.FileField(blank=True, null=True, upload_to='yudisium/perpus/pustaka/')),
                ('lampiran', models.FileField(blank=True, null=True, upload_to='yudisium/perpus/lampiran/')),
                ('jurnal_publikasi', models.FileField(blank=True, null=True, upload_to='yudisium/perpus/jurnal/')),
                ('lampiran_cetak', models.FileField(blank=True, null=True, upload_to='yudisium/perpus/lampiran_cetak/')),
                ('cek_plagiasi_jurnal', models.FileField(blank=True, null=True, upload_to='yudisium/perpus/plagiasi_jurnal/')),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak')], default='MENUNGGU', max_length=20)),
                ('catatan_perpus', models.TextField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('link_surat_pdf', models.CharField(blank=True, max_length=500, null=True)),
                ('ttd_petugas', models.CharField(blank=True, max_length=500, null=True)),
                ('ttd_position_x', models.IntegerField(default=50)),
                ('ttd_position_y', models.IntegerField(default=70)),
                ('validated_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['PERPUS', 'SUPERADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pendaftaran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perpus', to='sistem_yudisium.pendaftaranyudisium')),
            ],
        ),
        migrations.CreateModel(
            name='PendaftaranYudisiumFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('nim', models.CharField(max_length=20)),
                ('tempat_lahir', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('nik', models.CharField(max_length=16, unique=True)),
                ('nama_ibu_kandung', models.CharField(max_length=200)),
                ('nama_bapak_kandung', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu Verifikasi BAAK'), ('DISETUJUI', 'Disetujui / Diverifikasi BAAK'), ('DITOLAK', 'Ditolak')], default='MENUNGGU', max_length=20)),
                ('catatan_baak', models.TextField(blank=True, null=True)),
                ('tanggal_daftar', models.DateTimeField(auto_now_add=True)),
                ('tanggal_verifikasi', models.DateTimeField(blank=True, null=True)),
                ('mahasiswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran_final', to='sistem_yudisium.mahasiswa')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran_final', to='sistem_yudisium.periodeyudisium')),
            ],
            options={
                'verbose_name': 'Pendaftaran Yudisium Final',
                'verbose_name_plural': 'Pendaftaran Yudisium Final',
                'ordering': ['-tanggal_daftar'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatPendaftaranYudisium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_sebelum', models.CharField(max_length=20)),
                ('status_sesudah', models.CharField(max_length=20)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat', to='sistem_yudisium.pendaftaranyudisiumfinal')),
                ('petugas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranskripNilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nilai', models.JSONField(blank=True, default=list, null=True)),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak')], default='MENUNGGU', max_length=20)),
                ('catatan_baak', models.TextField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('pendaftaran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transkrip', to='sistem_yudisium.pendaftaranyudisium')),
                ('validated_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'BAAK'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
